import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Kasparro Crypto Sentinel", layout="wide")

st.title("🚀 Kasparro Crypto ETL Dashboard")
st.markdown("Real-time insights from the CoinGecko ETL pipeline.")

# Load the data generated by your ETL
try:
    df = pd.read_csv('crypto_data.csv')
    
    # Metrics
    col1, col2, col3 = st.columns(3)
    col1.metric("Latest Price (USD)", f"${df['price_usd'].iloc[-1]:,.2f}")
    col2.metric("24h Volume", f"${df['volume_24h'].iloc[-1]:,.0f}")
    col3.metric("Data Points", len(df))

    # Chart
    st.subheader("Price Trend")
    fig = px.line(df, x='timestamp', y='price_usd', title="Crypto Price over Time")
    st.plotly_chart(fig, use_container_width=True)

    # Data Table
    st.subheader("Raw Data")
    st.dataframe(df)

except FileNotFoundError:
    st.error("No data found! Run the ETL script first to generate crypto_data.csv.")